CREATE TABLE `MYCASH`.`DESPESA`(
`id` INT NOT NULL,
`VALOR` VARCHAR(255),
`TIPO` VARCHAR(100),
`DATA` VARCHAR(10),
`DESCRICAO` VARCHAR(255),
`FIXO` TINYINT NOT NULL,
PRIMARY KEY(`id`));

CREATE TABLE `MYCASH`.`RECEITA`(
`id` INT NOT NULL,
`VALOR` VARCHAR(255),
`TIPO` VARCHAR(100),
`DATA` VARCHAR(10),
`DESCRICAO` VARCHAR(255),
`FIXO` TINYINT NOT NULL,
PRIMARY KEY(`id`));

CREATE TABLE `MYCASH`.`TIPO`(
`id` INT NOT NULL,
`DESCRICAO` VARCHAR(255),
PRIMARY KEY(`id`));
